# Generated by Django 6.0.6 on 2026-07-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrador'), ('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente')], max_length=15),
        ),
    ]
