# Generated by Django 6.0.6 on 2026-06-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Fútbol 5', 'Fútbol 5'), ('Fútbol 7', 'Fútbol 7'), ('Fútbol 11', 'Fútbol 11')], max_length=20)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='canchas/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
