# Generated by Django 6.0.6 on 2026-06-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
